apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-postgres-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-postgres-crud
  template:
    metadata:
      labels:
        app: go-postgres-crud
    spec:
      containers:
        - name: go-postgres-crud
          image: ko://github.com/rkgcloud/crud/cmd/ # Ensure this matches your Docker image name and tag
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
